language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jeet' ]; then cd .. && eval "mv $currentfolder generator-jeet" && cd generator-jeet; fi

